---
version: '3.3'

services:
  dialog:
    container_name: dialog
    image: dialog
    build: ./
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./app/logs:/app/app/logs